source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MakeItHybrid_Example', :exclusive => true do
  pod "MakeItHybrid", :path => "../MakeItHybrid.podspec"
end

target 'MakeItHybrid_Tests', :exclusive => true do
  pod "MakeItHybrid", :path => "../MakeItHybrid.podspec"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
